services:
  postgres:
    container_name: DMS_DB
    image: postgres
    hostname: localhost
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./DataAccess/_Setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./DataAccess/_Setup/user.sql:/docker-entrypoint-initdb.d/users.sql
    restart: unless-stopped
    env_file:
      - .env

  pgadmin:
    container_name: DMS_DB-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped
    env_file:
      - .env

  linaksimulatorapi:
    container_name: LinakSimulatorAPI
    build:
      context: ./TableController/LinakSimulatorController
    ports:
      - "${LSAPI_PORT}:8433"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./TableController/LinakSimulatorController:/app
    working_dir: /app

volumes:
  postgres-data: 
    name: DMS-DB